// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Customer: typeof import('./../src/components/Popup/customer.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Footer: typeof import('./../src/layout/components/footer/Footer.vue')['default']
    Header: typeof import('./../src/layout/components/header/Header.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    History: typeof import('./../src/layout/components/header/History.vue')['default']
    IconPark: typeof import('./../src/components/IconPark/index.vue')['default']
    Menu: typeof import('./../src/layout/components/menu/Menu.vue')['default']
    MenuList: typeof import('./../src/layout/components/menu/MenuList.vue')['default']
    Popup: typeof import('./../src/components/Popup/popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPopup: typeof import('./../src/layout/components/header/SearchPopup.vue')['default']
  }
}
