// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Customer: typeof import('./components/Popup/customer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Popup: typeof import('./components/Popup/popup.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}

export { }
